name: Virus Scan

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: '0 0 * * *'  # Scan every day at midnight (UTC)

jobs:
  scan:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install VirusTotal CLI
      run: pip install vt-py

    - name: Scan code files
      run: vt scan ${{ github.workspace }}

    - name: Scan commit messages
      run: |
        git log --format=%B -n 1 ${{ github.sha }} | vt scan

    - name: Scan pull request diffs
      run: |
        git diff --name-only ${{ github.event.before }} ${{ github.sha }} | xargs vt scan
