name: Virus Scan

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: '0 0 * * *'  # Scan every day at midnight (UTC)

jobs:
  scan:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download and install ClamAV
      run: |
        Invoke-WebRequest -Uri "https://github.com/Cisco-Talos/clamav-win32/releases/download/v0.103.2/clamav-0.103.2-win-x64-portable.zip" -OutFile "clamav.zip"
        Expand-Archive -Path "clamav.zip" -DestinationPath "C:\clamav"
        Remove-Item "clamav.zip"

    - name: Update ClamAV database
      run: C:\clamav\clamav-0.103.2\bin\freshclam.exe

    - name: Scan code files
      run: C:\clamav\clamav-0.103.2\bin\clamscan.exe --recursive --bell --detect-pua --detect-structured --detect-ole2macros --follow-dir-symlinks --follow-file-symlinks --infected --suppress-ok-results .

    - name: Scan commit messages
      run: |
        git log --format=%B -n 1 ${{ github.sha }} | C:\clamav\clamav-0.103.2\bin\clamscan.exe -

    - name: Scan pull request diffs
      run: |
        git diff --name-only ${{ github.event.before }} ${{ github.sha }} | xargs C:\clamav\clamav-0.103.2\bin\clamscan.exe --
